imports:
    - { resource: service_converter_data.yml }
services:

    doctrine.dbal.config:
        class: Doctrine\DBAL\Configuration

    doctrine.dbal.drivermanager:
        class: Doctrine\DBAL\DriverManager

    phpbb.installer.converter.bin.converter:
        class: phpbb\install\converter\bin\converter
        arguments:
            - '@phpbb.dbal.source.connection'
            - '@phpbb.dbal.destination.connection'
            - '@installer.helper.iohandler_factory'
            - '@phpbb.installer.converter.controller.helper'
            - '%core.root_path%'


    phpbb.dbal.source.connection:
        class: phpbb\install\converter\connection
        factory: ['phpbb\install\converter\factory\dbal_connection_source_factory',get_connection]
        arguments: ['@doctrine.dbal.config','@phpbb.installer.converter.controller.helper']

    phpbb.dbal.destination.connection:
            class: phpbb\install\converter\connection
            factory: ['phpbb\install\converter\factory\dbal_connection_destination_factory',get_connection]
            arguments: ['@doctrine.dbal.config','@phpbb.installer.converter.controller.helper']

    phpbb.installer.converter.controller.helper:
        class: phpbb\install\converter\controller\helper
        arguments:
            - '@installer.helper.config'
            - '@language'
            - '@language.helper.language_file'
            - '@installer.navigation.provider'
            - '@template'
            - '@path_helper'
            - '@request'
            - '@symfony_request'
            - '@router'
            - '%core.root_path%'

    phpbb.installer.converter.index:
        class: phpbb\install\converter\controller\converter_index
        arguments:
            - '@phpbb.installer.converter.controller.helper'
            - '@installer.helper.container_factory'
            - '@installer.navigation.provider'
            - '@language'
            - '@template'
            - '@converter.module.obtain_data'
            - '@installer.helper.config'
            - '@installer.helper.iohandler_factory'
            - '%core.root_path%'
            - '%core.php_ext%'

    phpbb.installer.converter.convert:
        class: phpbb\install\converter\controller\controller_convert
        arguments:
            - '@phpbb.installer.converter.bin.converter'
            - '@phpbb.installer.converter.controller.helper'
            - '@installer.navigation.provider'
            - '@installer.helper.iohandler_factory'
            - '@request'
            - '@language'
            - '@template'
            - '%core.root_path%'
            - '%core.php_ext%'

    phpbb.installer.converter.start:
        class: phpbb\install\converter\controller\converter_start
        arguments:
            - '@phpbb.installer.converter.bin.converter'
            - '@phpbb.installer.converter.controller.helper'
            - '@installer.navigation.provider'
            - '@installer.helper.iohandler_factory'
            - '@installer.helper.config'
            - '@converter.module.obtain_data'
            - '@request'
            - '@language'
            - '@installer.helper.container_factory'
            - '@template'
            - '%core.root_path%'
