services:
    converter.task.do.conversion:
        class: phpbb\install\converter\module\converter_convert\task\convert
        arguments:
            - '@phpbb.installer.converter.bin.converter'
            - '@phpbb.installer.converter.controller.helper'
            - '@installer.helper.config'
            - '@installer.helper.iohandler'
            - '@installer.helper.container_factory'
            - '%core.root_path%'
        tags:
            - { name: converter_convert, order: 10 }

    converter.module.converter_convert_collection:
            class: phpbb\di\ordered_service_collection
            arguments:
                - '@service_container'
            tags:
                - { name: service_collection, tag: converter_convert, class_name_aware: true }

    converter.module.converter_convert:
        class: phpbb\install\converter\module\converter_convert\module
        arguments:
                - '@converter.module.converter_convert_collection'
        tags:
            - { name: converter_module, order: 20 }



